services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloakpass
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminpass
    ports:
      - "8080:8080"
    command: ["start-dev"]
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloakpass
  reverseproxyserver:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./reverseproxyserver/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
  clientserver:
    build: ./clientserver
    container_name: clientserver
    volumes:
      - ./clientserver:/app
    ports:
      - "8000:8000"
